"use client";
import { useMemo, useState } from "react";

type Budget = { transport:number; hotel:number; food:number; tickets:number; shopping:number; misc:number };
const cities = [{ name:"三亚", days:5, people:2, hotel:650, food:260, tickets:180, transport:900 },{ name:"成都", days:4, people:2, hotel:420, food:180, tickets:120, transport:500 },{ name:"东京", days:6, people:2, hotel:900, food:320, tickets:240, transport:2600 },{ name:"大理", days:4, people:2, hotel:360, food:160, tickets:100, transport:650 }];
const money = (n:number) => `¥${Math.round(n).toLocaleString("zh-CN")}`;
export default function Home(){
 const [destination,setDestination]=useState("三亚"); const [days,setDays]=useState(5); const [people,setPeople]=useState(2); const [style,setStyle]=useState("舒适"); const [showShare,setShowShare]=useState(false);
 const city=cities.find(c=>c.name===destination) || cities[0];
 const budget=useMemo<Budget>(()=>{const factor=style==="省钱"?.72:style==="舒适"?1:1.55; return {transport:city.transport*factor,hotel:city.hotel*(days-1)*factor,food:city.food*days*factor,tickets:city.tickets*days/5*factor,shopping:300*people*factor,misc:180*factor};},[city,days,people,style]);
 const total=Object.values(budget).reduce((a,b)=>a+b,0); const perDay=total/days;
 const shareText=`${destination}${days}天${people}人旅行，预计花费 ${money(total)}。住宿 ${money(budget.hotel)}，吃饭 ${money(budget.food)}，交通 ${money(budget.transport)}。`;
 const copy=async()=>{await navigator.clipboard?.writeText(shareText); setShowShare(true);};
 return <main className="shell"><header><div className="brand"><span>¥</span><b>旅费有数</b></div><span className="tag">出发前，先知道要花多少</span></header><section className="hero"><div><p className="kicker">TRIP BUDGET / 01</p><h1>这趟旅行，<br/><em>大概要花多少？</em></h1><p className="lead">输入几个数字，得到一份可以带走的旅行预算。</p></div><div className="orbit"><span>先算<br/>再出发</span></div></section><section className="workspace"><div className="form card"><p className="kicker">你的旅行</p><label>去哪里<select value={destination} onChange={e=>setDestination(e.target.value)}>{cities.map(c=><option key={c.name}>{c.name}</option>)}</select></label><div className="two"><label>玩几天<input type="number" min="1" max="30" value={days} onChange={e=>setDays(Number(e.target.value)||1)}/></label><label>几个人<input type="number" min="1" max="20" value={people} onChange={e=>setPeople(Number(e.target.value)||1)}/></label></div><label>旅行风格<div className="seg">{["省钱","舒适","放松"].map(s=><button className={style===s?"active":""} key={s} onClick={()=>setStyle(s)}>{s}</button>)}</div></label><p className="hint">当前使用城市消费档位估算，实际价格会随日期变化。</p></div><div className="result"><div className="result-head"><div><p className="kicker">预计总花费</p><strong>{money(total)}</strong><span>约 {money(perDay)} / 天</span></div><div className="badge">{style}版</div></div><div className="bars">{Object.entries(budget).map(([key,value])=><div className="bar" key={key}><div><span>{{transport:"交通",hotel:"住宿",food:"餐饮",tickets:"门票",shopping:"购物",misc:"机动"}[key as keyof Budget]}</span><b>{money(value)}</b></div><i><u style={{width:`${Math.max(8,value/total*100)}%`}}/></i></div>)}</div><button className="share" onClick={copy}>生成我的旅行预算卡 <span>↗</span></button></div></section><section className="trip-note"><span>旅行预算不是限制，是让你放心出发。</span><b>旅费有数 · beta</b></section>{showShare&&<div className="mask" onClick={()=>setShowShare(false)}><div className="share-card" onClick={e=>e.stopPropagation()}><p className="kicker">MY TRIP BUDGET</p><h2>{destination}<br/><em>{days}天 · {people}人</em></h2><strong>{money(total)}</strong><span>预计总花费</span><p>{shareText}</p><button onClick={()=>setShowShare(false)}>返回计算</button></div></div>}</main>
}
